### PR TITLE
fix: sort far-future date groups chronologically (Issue #183)

### LINKED ISSUE #183: Bug: Far-future date groups not sorted chronologically
## Description
In Schedule.jsx, groupOrders buckets dates into 'Overdue', 'Today', 'Tomorrow', or 'This Week' for the first 7 days. Anything beyond 7 days gets a label formatted as a specific date string. These labels are not in the GROUP_ORDER constant, so when the sort comparator encounters two of them it falls through to return 0, which tells the sort they are equal. This causes far-future date groups to appear in seemingly random order.

## Trigger
The selected day window is wide enough to include orders more than 7 days out (14-day or 30-day view), and there are at least two orders on different far-future dates.

## Example
With the 30-day window and orders on Apr 10, Apr 18, and May 2, the groups could render as:
- This Week
- Mon, May 2 (wrong, should be last)
- Thu, Apr 10 (wrong)
- Fri, Apr 18

## Current Code (lines ~460-470)
The sort comparator returns 0 for far-future date groups.

## Fix
Replace the return 0 fallback with a date comparison:
```js
const aDate = new Date(groups[a][0].scheduled_date);
const bDate = new Date(groups[b][0].scheduled_date);
return aDate - bDate;
```

### PR DESCRIPTION
**Pull request by ramishk12**
## Summary
- Fixes Issue #183: Far-future date groups not sorted chronologically
- Replaced the return 0 fallback with a date comparison using the first order's scheduled_date
- Far-future date groups now sort correctly by date
- Build passes successfully

Closes #183

### CODE REVIEW

File: web/src/pages/Schedule.jsx [hunk 1]
```diff
@@ -70,7 +70,9 @@ function groupOrders(orders) {
     if (ai !== -1 && bi !== -1) return ai - bi;
     if (ai !== -1) return -1;
     if (bi !== -1) return 1;
-    return 0;
+    const aDate = new Date(groups[a][0].scheduled_date);
```
Comment (ramishk12) [inline web/src/pages/Schedule.jsx]:
```suggestion
    // Both are far-future date labels — sort by the date of the first order in each group
    const aDate = new Date(groups[a][0].scheduled_date);
```
